export const TOOLKIT_ITEMS = [
  {
    id: 'universe',
    title: 'Risk Universe Template',
    tier: 'free',
    desc: 'Map all auditable entities. KIAM Section 3.2.',
    content: {
      type: 'table',
      headers: ['Quadrant', 'Category', 'Auditable Entities', 'Risk Rating'],
      rows: [
        ['Core Operations', 'HR & People', 'Payroll, Recruitment, Training, Performance management', 'Medium'],
        ['Core Operations', 'Finance', 'GL, AP, AR, Treasury, Fixed assets, Tax compliance', 'High'],
        ['Core Operations', 'IT', 'ERP systems, Cybersecurity, Change management, BCP/DR', 'High'],
        ['Core Operations', 'Operations', 'Procurement, Inventory, Production, Quality, Logistics', 'High'],
        ['Core External', 'Regulatory', 'Central bank compliance, Licensing, AML/KYC', 'High'],
        ['Core External', 'Market', 'Competition, Customer concentration, Pricing pressure', 'Medium'],
        ['Core External', 'Third Party', 'Vendor management, Outsourcing, SLA monitoring', 'Medium'],
        ['Emerging', 'ESG', 'Climate reporting, Social impact, Governance disclosure', 'Medium'],
        ['Emerging', 'AI/Technology', 'AI governance, Data privacy, Algorithmic bias, GDPR', 'High'],
        ['Emerging', 'Geopolitical', 'Sanctions, Supply chain disruption, Regional instability', 'Medium'],
        ['Business Change', 'M&A', 'Due diligence, Integration, Synergy tracking', 'High'],
        ['Business Change', 'Transformation', 'ERP migration, Process reengineering, Restructuring', 'High'],
      ],
    },
  },
  {
    id: 'assessment',
    title: 'Risk Assessment Framework',
    tier: 'free',
    desc: '5x5 matrix with defined scales. Inherent to residual methodology.',
    content: {
      type: 'matrix',
      likelihood: [
        { score: 1, label: 'Rare', def: '<5% probability within 12 months' },
        { score: 2, label: 'Unlikely', def: '5-20% probability' },
        { score: 3, label: 'Possible', def: '20-50% probability' },
        { score: 4, label: 'Likely', def: '50-80% probability' },
        { score: 5, label: 'Almost Certain', def: '>80% probability' },
      ],
      impact: [
        { score: 1, label: 'Negligible', def: 'Minimal financial/operational impact' },
        { score: 2, label: 'Minor', def: 'Contained within department' },
        { score: 3, label: 'Moderate', def: 'Affects multiple functions' },
        { score: 4, label: 'Significant', def: 'Requires executive attention' },
        { score: 5, label: 'Severe', def: 'Threatens strategic objectives' },
      ],
      zones: { red: '20-25', amber: '10-19', yellow: '5-9', green: '1-4' },
    },
  },
  {
    id: 'racm',
    title: 'Risk & Control Matrix (RACM)',
    tier: 'pro',
    desc: 'Process-to-test mapping. KIAM Section 6.4.',
    content: {
      type: 'table',
      headers: ['Process Step', 'Risk', 'Control', 'Type', 'Test Procedure'],
      rows: [
        ['Purchase requisition', 'Unauthorised purchases', 'Budget holder approves all POs >$5K', 'Preventive/Manual', 'Select 25 POs >$5K; verify approval signature + authority matrix'],
        ['Vendor selection', 'Fraudulent vendors', 'Approved vendor list maintained by procurement', 'Preventive/Manual', 'Select 15 new vendors; verify approval + due diligence docs'],
        ['PO creation', 'Duplicate orders', 'System blocks duplicate PO numbers', 'Preventive/Auto', 'Attempt to create duplicate PO in test environment; verify rejection'],
        ['Goods receipt', 'Receiving incorrect goods', 'Three-way match: PO vs GRN vs Invoice', 'Detective/ITDM', 'Select 25 invoices; verify 3-way match documentation'],
        ['Invoice processing', 'Overpayment', 'Invoice tolerance check (5% variance)', 'Detective/Auto', 'Review system tolerance settings; test 10 invoices near threshold'],
        ['Payment approval', 'Unauthorised payments', 'Dual authorisation for payments >$10K', 'Preventive/Manual', 'Select 20 payments >$10K; verify dual sign-off'],
      ],
    },
  },
  {
    id: 'planning',
    title: 'Audit Planning Checklist',
    tier: 'pro',
    desc: '10-item pre-engagement checklist. KIAM Section 5.',
    content: {
      type: 'checklist',
      items: [
        { item: 'Terms of Reference drafted and agreed', owner: 'EL', status: 'template' },
        { item: 'RACM completed for in-scope processes', owner: 'EM', status: 'template' },
        { item: 'Client documentation requested', owner: 'TM', status: 'template' },
        { item: 'Kick-off meeting scheduled', owner: 'EM', status: 'template' },
        { item: 'Resource plan confirmed (team, timeline, budget)', owner: 'EL', status: 'template' },
        { item: 'Prior year findings reviewed for follow-up', owner: 'TM', status: 'template' },
        { item: 'Data analytics requirements identified', owner: 'TM', status: 'template' },
        { item: 'Scope variations documented and approved', owner: 'EL', status: 'template' },
        { item: 'Fieldwork schedule communicated to client', owner: 'EM', status: 'template' },
        { item: 'Working paper templates prepared', owner: 'TM', status: 'template' },
      ],
    },
  },
  {
    id: 'fieldwork',
    title: 'Fieldwork Procedures Library',
    tier: 'toolkit',
    desc: 'Test procedures by process area. KIAM Section 6.5.',
    content: { type: 'locked' },
  },
  {
    id: 'workingpapers',
    title: 'Working Paper Templates',
    tier: 'toolkit',
    desc: '6-section structure per KIAM Section 6.5.1.',
    content: { type: 'locked' },
  },
  {
    id: 'obslog',
    title: 'Observation & Change Log',
    tier: 'toolkit',
    desc: 'Real-time issue tracking. KIAM Section 6.6.',
    content: { type: 'locked' },
  },
  {
    id: 'reporting',
    title: 'Reporting Templates',
    tier: 'toolkit',
    desc: 'Executive summary + CCER findings + action plan. KIAM Section 7.',
    content: { type: 'locked' },
  },
];
